[build-system]
requires = ["flit_core >=3.2,<4",
            "sphinx_rtd_theme",
            "myst-parser"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Juan David Guerrero", email = "juan.guerrero@polito.it"}]
dynamic = ["version", "description"]
